import { useMemo, useRef, useState } from 'react'
import { BookHeart, FileJson, LockKeyhole, Search, Sparkles, Upload, X } from 'lucide-react'
import { analyze, parseChat } from './analyze'
import { recognizeScreenshots, type OcrStatus } from './ocr'
import { sample } from './sample'
import { SignalLamp } from './SignalLamp'
import type { Candidate, Message } from './types'

export function App() {
  const [messages, setMessages] = useState<Message[]>([])
  const [filename, setFilename] = useState('')
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('全部')
  const [selected, setSelected] = useState<Candidate | null>(null)
  const [error, setError] = useState('')
  const [ocrStatus, setOcrStatus] = useState<OcrStatus | null>(null)
  const [view, setView] = useState<'dictionary' | 'signal'>('dictionary')
  const input = useRef<HTMLInputElement>(null)
  const candidates = useMemo(() => analyze(messages), [messages])
  const shown = candidates.filter(x => (category === '全部' || x.category === category) && x.phrase.includes(query))
  const load = (raw: unknown, name: string) => { try { const rows = parseChat(raw); if (!rows.length) throw new Error('文件中没有可分析的文本消息。'); setMessages(rows); setFilename(name); setError('') } catch (e) { setError(e instanceof Error ? e.message : '无法读取文件') } }
  const onFile = async (e: React.ChangeEvent<HTMLInputElement>) => { const file = e.target.files?.[0]; if (!file) return; try { load(JSON.parse(await file.text()), file.name) } catch { setError('JSON 格式无效，请检查文件内容。') }; e.target.value = '' }
  const onImages = async (files: FileList | File[]) => { const images = Array.from(files).filter(file => file.type.startsWith('image/')); if (!images.length) return; try { setError(''); setOcrStatus({ progress: 0, label: '正在准备截图…' }); const rows = await recognizeScreenshots(images, setOcrStatus); if (!rows.length) throw new Error('未能识别到可归属的文字气泡，请确认截图中包含左右消息气泡。'); setMessages(rows); setFilename(`${images.length} 张聊天截图（OCR）`) } catch (e) { setError(e instanceof Error ? e.message : `截图识别失败：${String(e)}`) } finally { setOcrStatus(null) } }
  if (view === 'signal') return <SignalLamp onBack={() => setView('dictionary')} />
  if (!messages.length) return <main className="landing"><nav><div className="brand"><BookHeart /> 两个人的词典</div><button className="signalNav" onClick={() => setView('signal')}>♥ 恋爱信号灯</button><span className="privacy"><LockKeyhole size={15} /> 数据仅在此设备处理</span></nav><section className="hero"><div className="eyebrow"><Sparkles size={14} /> 把日常，编成只有你们懂的词典</div><h1>每一句熟悉的话，<br /><em>都有它的故事。</em></h1><p>导入微信聊天 JSON 或截图，在本地发现你们的昵称、口头禅、固定短语与共同记忆。</p><div className="importGrid"><div className="drop" onClick={() => input.current?.click()} onDragOver={e => e.preventDefault()} onDrop={async e => { e.preventDefault(); const file = e.dataTransfer.files[0]; if (file) try { load(JSON.parse(await file.text()), file.name) } catch { setError('JSON 格式无效，请检查文件内容。') } }}><div className="uploadIcon"><FileJson /></div><b>导入 chat.json</b><span>支持 wx-cli 导出的 JSON 文件</span><button>选择 JSON</button><input ref={input} hidden type="file" accept=".json,application/json" onChange={onFile} /></div><label className="drop imageDrop" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); onImages(e.dataTransfer.files) }}><div className="uploadIcon"><Upload /></div><b>拖入聊天截图</b><span>PNG、JPG；可一次选择多张</span><span className="autoSender">自动区分：左侧灰色气泡为对方，右侧绿色气泡为我</span><button type="button">选择截图</button><input hidden type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={e => { if (e.target.files) onImages(e.target.files); e.target.value = '' }} /></label></div>{ocrStatus && <div className="ocrStatus"><b>{ocrStatus.label} {Math.round(ocrStatus.progress * 100)}%</b><div><i style={{ width: `${ocrStatus.progress * 100}%` }} /></div><span>中文模型在本机加载，截图不会上传。</span></div>}{error && <p className="error">{error}</p>}<button className="sample" onClick={() => load(sample, '示例聊天.json')}>没有文件？体验示例数据 →</button><div className="command"><span>截图建议：保留完整左右聊天气泡，时间分隔线和表情消息会自动跳过。</span></div></section></main>
  return <main><nav><div className="brand"><BookHeart /> 两个人的词典</div><div className="navRight"><span className="privacy"><LockKeyhole size={15} /> 仅本地处理</span><button className="ghost" onClick={() => { setMessages([]); setSelected(null) }}>更换文件</button></div></nav><div className="shell"><header className="summary"><div><div className="eyebrow">OUR LITTLE LANGUAGE</div><h1>你们的专属词典</h1><p>从 <b>{messages.length}</b> 条文字消息里，发现了 <b>{candidates.length}</b> 个值得收藏的表达。</p></div><div className="filePill"><FileJson /><span><b>{filename}</b><small>{new Set(messages.map(x => x.sender)).size} 位聊天者 · 本地分析完成</small></span></div></header><div className="toolbar"><label><Search size={18} /><input placeholder="搜索一个词…" value={query} onChange={e => setQuery(e.target.value)} /></label><div className="tabs">{['全部', '昵称', '口头禅', '固定短语', '共同记忆'].map(x => <button className={category === x ? 'active' : ''} onClick={() => setCategory(x)} key={x}>{x}</button>)}</div></div><section className="grid">{shown.map((c, i) => <article onClick={() => setSelected(c)} key={c.phrase}><div className="cardTop"><span className={'tag t' + c.category}>{c.category}</span><span className="rank">#{i + 1}</span></div><h2>{c.phrase}</h2><p className="meaning">“{c.topUser} 常挂在嘴边的两人暗号。”</p><div className="metric"><strong>{c.count}</strong><span>次出现</span><i /><strong>{c.topUser}</strong><span>最常说</span></div>{c.collocations.length > 0 && <div className="chips">常搭配 {c.collocations.map(x => <span key={x}>{x}</span>)}</div>}</article>)}</section>{!shown.length && <div className="empty">没有匹配的候选词，换个筛选条件试试。</div>}</div>{selected && <div className="overlay" onClick={() => setSelected(null)}><aside onClick={e => e.stopPropagation()}><button className="close" onClick={() => setSelected(null)}><X /></button><span className={'tag t' + selected.category}>{selected.category}</span><h2>{selected.phrase}</h2><p className="lead">这是一个出现了 {selected.count} 次的专属表达，最常由 {selected.topUser} 使用。</p><h3>谁在说</h3>{Object.entries(selected.users).sort((a, b) => b[1] - a[1]).map(([user, count]) => <div className="bar" key={user}><span>{user}</span><div><i style={{ width: `${count / selected.count * 100}%` }} /></div><b>{count} 次</b></div>)}<h3>典型上下文</h3>{selected.contexts.map((m, i) => <blockquote key={i}><b>{m.sender}</b><p>{m.content}</p>{m.time && <small>{m.time}</small>}</blockquote>)}<p className="localNote"><LockKeyhole size={14} /> 上下文没有离开你的浏览器</p></aside></div>}</main>
}
